### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Gert-dev** [limemloh/monkey-jump#1]
Hi

Just installed this package to try it out. On pressing the `Ctrl-Y` shortcut, I immediately get the following error in any document:

```
TypeError: Cannot read property 'split' of undefined
    at HTMLElement.jump (/home/user/.atom/packages/monkey-jump/lib/index.ts:252:56)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:384:43)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:110:34)
```

**Comment by limemloh** [comment]
Hey
Thank you for making me aware of this.

I have discovered that my developing environment behaves very differently from a clean Atom and fixed multiple bugs. 

Please try updating `monkey-jump` to version 0.3.10

**Comment by Gert-dev** [comment]
That fixes it, thanks!
